/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PBBP2_PBBP2_PB_H_INCLUDED
#define PB_PBBP2_PBBP2_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _pbbp2_Header {
    pb_callback_t key;
    pb_callback_t value;
} pbbp2_Header;

typedef struct _pbbp2_Frame {
    int64_t SeqID;
    int64_t LogID;
    int32_t service;
    int32_t method;
    pb_callback_t headers;
    pb_callback_t payload_encoding;
    pb_callback_t payload_type;
    pb_callback_t payload;
    pb_callback_t LogIDNew;
} pbbp2_Frame;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define pbbp2_Header_init_default                {{{NULL}, NULL}, {{NULL}, NULL}}
#define pbbp2_Frame_init_default                 {0, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define pbbp2_Header_init_zero                   {{{NULL}, NULL}, {{NULL}, NULL}}
#define pbbp2_Frame_init_zero                    {0, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define pbbp2_Header_key_tag                     1
#define pbbp2_Header_value_tag                   2
#define pbbp2_Frame_SeqID_tag                    1
#define pbbp2_Frame_LogID_tag                    2
#define pbbp2_Frame_service_tag                  3
#define pbbp2_Frame_method_tag                   4
#define pbbp2_Frame_headers_tag                  5
#define pbbp2_Frame_payload_encoding_tag         6
#define pbbp2_Frame_payload_type_tag             7
#define pbbp2_Frame_payload_tag                  8
#define pbbp2_Frame_LogIDNew_tag                 9

/* Struct field encoding specification for nanopb */
#define pbbp2_Header_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   key,               1) \
X(a, CALLBACK, REQUIRED, STRING,   value,             2)
#define pbbp2_Header_CALLBACK pb_default_field_callback
#define pbbp2_Header_DEFAULT NULL

#define pbbp2_Frame_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT64,    SeqID,             1) \
X(a, STATIC,   REQUIRED, INT64,    LogID,             2) \
X(a, STATIC,   REQUIRED, INT32,    service,           3) \
X(a, STATIC,   REQUIRED, INT32,    method,            4) \
X(a, CALLBACK, REPEATED, MESSAGE,  headers,           5) \
X(a, CALLBACK, OPTIONAL, STRING,   payload_encoding,   6) \
X(a, CALLBACK, OPTIONAL, STRING,   payload_type,      7) \
X(a, CALLBACK, OPTIONAL, BYTES,    payload,           8) \
X(a, CALLBACK, OPTIONAL, STRING,   LogIDNew,          9)
#define pbbp2_Frame_CALLBACK pb_default_field_callback
#define pbbp2_Frame_DEFAULT NULL
#define pbbp2_Frame_headers_MSGTYPE pbbp2_Header

extern const pb_msgdesc_t pbbp2_Header_msg;
extern const pb_msgdesc_t pbbp2_Frame_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define pbbp2_Header_fields &pbbp2_Header_msg
#define pbbp2_Frame_fields &pbbp2_Frame_msg

/* Maximum encoded size of messages (where known) */
/* pbbp2_Header_size depends on runtime parameters */
/* pbbp2_Frame_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
