/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "pbbp2.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(pbbp2_Header, pbbp2_Header, AUTO)


PB_BIND(pbbp2_Frame, pbbp2_Frame, AUTO)



